[project]
name = "AIhub-Afdian"
version = "0.1.0"
description = "爱发电 Webhook 自动生成 New API 兑换码"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "pydantic>=2.0.0",
    "uvicorn[standard]>=0.52.1",
    "python-dotenv>=1.2.2",
    "slowapi>=0.1.10",
    "limits>=5.8.0",
    "aiosmtplib>=5.1.2",
    "email-validator>=2.3.0"
]

[tool.ruff]
line-length = 79
target-version = "py312"
extend-exclude = [".venv"]

[tool.ruff.lint]
select = ["E", "F", "UP"]

[tool.ruff.format]
quote-style = "single"

[tool.pytest.ini_options]
asyncio_mode = "auto"

[tool.scripts]
build-venv = "python -m venv .venv"
requirements = "pip freeze > requirements.txt"
check = "ruff format --check ."
format = "ruff format ."
test-all = "pytest tests/"
test-api = "pytest tests/test_api.py"

[tool.vercel]
entrypoint = "main:app"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "ruff>=0.16.2",
    "toml-run>=0.0.2",
]
